services:
    php:
        build:
            context: docker/php
            target: dev-php
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        depends_on:
            minio:
                condition: service_healthy
        tty: true
        command: rr serve -d -c .rr.dev.yaml
        environment:
            COMPOSER_ROOT_VERSION: ${COMPOSER_ROOT_VERSION:-1.0}
            WELCOME_MESSAGE: "Hello PHP Russia 2024"
        volumes:
            - .:/app:cached
            - ~/.composer:/var/www/.composer
        extra_hosts:
            - s3.php-russia-2024-symfony.local:host-gateway
        labels:
            - traefik.enable=true
            - traefik.http.routers.php.service=php
            - traefik.http.routers.php.entryPoints=https
            - traefik.http.routers.php.rule=Host(`api.php-russia-2024-symfony.local`)
            - traefik.http.routers.php.tls=true
            - traefik.http.services.php.loadBalancer.server.port=80

    php-daemon:
        build:
            context: docker/php
            target: dev-php
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        depends_on:
            minio:
                condition: service_healthy
        tty: true
        command: rr serve -d -c .rr.dev.daemon.yaml
        volumes:
            - .:/app:cached

    minio:
        image: minio/minio:RELEASE.2024-10-02T17-50-41Z
        command: server --console-address ":9001" /data/
        healthcheck:
            test: [ "CMD", "mc", "ready", "local" ]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            MINIO_ROOT_USER: ${S3_USER}
            MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
        volumes:
            - minio:/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.minio.service=minio
            - traefik.http.routers.minio.entryPoints=https
            - traefik.http.routers.minio.rule=Host(`minio.php-russia-2024-symfony.local`)
            - traefik.http.routers.minio.tls=true
            - traefik.http.services.minio.loadBalancer.server.port=9001
            - traefik.http.routers.s3.service=s3
            - traefik.http.routers.s3.entryPoints=https
            - traefik.http.routers.s3.rule=Host(`s3.php-russia-2024-symfony.local`)
            - traefik.http.routers.s3.tls=true
            - traefik.http.services.s3.loadBalancer.server.port=9000

    traefik:
        image: traefik:v3.0
        command:
            - --api.insecure=true
            - --providers.file.filename=/config/config.toml
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.http.address=:80
            - --entrypoints.http.http.redirections.entrypoint.to=https
            - --entrypoints.http.http.redirections.entrypoint.scheme=https
            - --entrypoints.https.address=:443
        ports:
            - '443:443'
            - '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker/traefik:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entryPoints=https
            - traefik.http.routers.traefik.rule=Host(`traefik.php-russia-2024-symfony.local`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.services.traefik.loadBalancer.server.port=8080

volumes:
    minio: null