services:
    php:
        image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
        restart: always
        environment:
            COMPOSER_ROOT_VERSION: ${COMPOSER_ROOT_VERSION:-1.0}
            WELCOME_MESSAGE: ${WELCOME_MESSAGE:-default}
            APP_ENV: prod
        ports:
            - '127.0.0.1:8088:80'